CREATE TABLE IF NOT EXISTS facilities (
    id         VARCHAR(36) PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT,
    UNIQUE KEY uq_facilities_name (name)
);

-- Seed default facilities (ignore if already exists)
INSERT IGNORE INTO facilities (id, name, created_at)
VALUES
    (UUID(), 'AC', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'HDMI', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'LAYAR TV', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'LAYAR VIDETRON', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'LAYAR PROYEKTOR', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'SPLITER', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'PERANGKAT VIDEO CONFERENCE', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'MIC', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'SPEAKER', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'POINTER', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000),
    (UUID(), 'FLIPCHART', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000);
